# config file containing parameters
configfile: "config/config.yml"

# Include all rules for designing the screen
include: "rules/design_screen/k562_creating_targets.smk"

# Include all rules for processing validation datasets
include: "rules/process_validation_datasets/sceptre_setup.smk"
include: "rules/process_validation_datasets/sceptre_power_analysis.smk"

# Include all rules for benchmarking
include: "rules/benchmark_validation_datasets/create_encode_output.smk"
include: "rules/benchmark_validation_datasets/crispr_benchmarking.smk"

# Include all rules for analyzing validation datasets
# include: "rules/analyze_validation_datasets/process_bam_files_and_combined_w_EG_results.smk" # Removed because Maya running categorization of elements
include: "rules/analyze_validation_datasets/duplicate_pairs_analysis.smk"
include: "rules/analyze_validation_datasets/dc_tap_plots.smk"
include: "rules/analyze_validation_datasets/running_qcs_for_dc_tap_plots.smk"

# Perform all analyses to output benchmarked datasets
rule all:
  input: 
    # "results/analyze_validation_datasets/dc_tap_plots/summary_stats.txt",
    "results/analyze_validation_datasets/dc_tap_plots/check_negative_control_results/k562_volcano.pdf",
    "results/analyze_validation_datasets/duplicate_pairs_analysis/comparing_all_duplicate_pairs.pdf",
    "results/analyze_validation_datasets/dc_tap_plots/compare_replicates/k562_plot.pdf",
    "results/analyze_validation_datasets/dc_tap_plots/distance_by_effect_size_plots/k562_distance_by_es.pdf",
    "results/analyze_validation_datasets/dc_tap_plots/qPCR_qc/comparison_of_all_by_type.pdf"
  













