# config file containing parameters
configfile: "config/config.yml"

# Include all rules for processing validation datasets
include: "rules/sceptre_setup.smk"
include: "rules/sceptre_power_analysis.smk"

# Include all rules for formatting
include: "rules/create_encode_output.smk"
include: "rules/formatting_dc_tap_results.smk"

# # Include all rules for analyzing validation datasets
# include: "rules/analyze_validation_datasets/duplicate_pairs_analysis.smk"
# include: "rules/analyze_validation_datasets/dc_tap_plots.smk"
# include: "rules/analyze_validation_datasets/running_qcs_for_dc_tap_plots.smk"

# Perform all analyses to output benchmarked datasets
rule all:
  input: "results/formatted_dc_tap_results/Final_DC_TAP_Seq_Results_w_Chromatin_Categories_on_resized_elements.tsv"

