# config file containing parameters
configfile: "config/config.yml"

# Include all rules for processing validation datasets
include: "rules/sceptre_setup.smk"
include: "rules/sceptre_power_analysis.smk"

# Include all rules for formatting
include: "rules/create_encode_output.smk"
include: "rules/formatting_dc_tap_results.smk"

# Include all rules for creating paper items
include: "rules/supplementary_tables.smk"
include: "rules/main_figure_1_and_2.smk"
include: "rules/main_figure_3.smk"
include: "rules/duplicate_pairs_analysis.smk"

# Perform all analyses to output benchmarked datasets
rule all:
  input:
    "results/formatted_dc_tap_results/Final_DC_TAP_Seq_Results_w_Chromatin_Categories_on_resized_and_merged_elements.tsv",
    "results/supplementary_tables/create_all_supplementary_tables.done",
    "results/main_figure_1_and_2/create_main_figure_1_and_2.done"

# Main Figure 2
rule create_main_figure_1_and_2:
  input:
    # Figure 1 plot
    dc_tap_x_qpcr_fig1 = "results/main_figure_1_and_2/compare_k562_effect_sizes_to_qPCR/comparison_positive_controls.pdf",
    wtc11_multi_moi_fig1 = "results/main_figure_1_and_2/wtc11_multi_moi.pdf",
    read_umi_saturation_comparison = "results/main_figure_1_and_2/downsampling_reads_for_UMIs/read_umi_saturation_comparison.pdf",
    # Figure 2 plots
    k562_distance_by_es_fig2 = "results/main_figure_1_and_2/k562_distance_by_es.pdf",
    wtc11_distance_by_es_fig2 = "results/main_figure_1_and_2/wtc11_distance_by_es.pdf",
    effect_size_plot_fig2 = "results/main_figure_1_and_2/effect_size_boxplot.pdf",
    positive_control_self_promoters_effect_size_plot_fig2 = "results/main_figure_1_and_2/positive_control_self_promoters_effect_size_boxplot.pdf",
    k562_replicates_fig2 = "results/main_figure_1_and_2/compare_replicates/k562_plot.pdf", 
    wtc11_replicates_fig2 = "results/main_figure_1_and_2/compare_replicates/wtc11_plot.pdf", 
    dc_tap_x_qpcr_fig2 = "results/main_figure_1_and_2/compare_k562_effect_sizes_to_qPCR/comparison_others.pdf",
    duplicates_plot_fig2 = "results/main_figure_1_and_2/duplicate_pairs_analysis/duplicate_pairs.pdf"
  output:
    touch("results/main_figure_1_and_2/create_main_figure_1_and_2.done")
    
# Main Figure 3
rule create_main_figure_3:
  input:
    effect_size_comparison = "results/main_figure_3/compare_effect_sizes_to_other_screens/effect_size_comparison.pdf",
    power_for_all_datasets_by_proportion = "results/main_figure_3/power_to_detect_change_for_all_datasets/power_for_all_datasets_by_proportion.pdf",
    power_for_all_datasets_by_count = "results/main_figure_3/power_to_detect_change_for_all_datasets/power_for_all_datasets_by_count.pdf"
  output:
    touch("results/main_figure_3/craete_main_figure_3.done")
    
# Create the supplementary tables
rule create_all_supplementary_tables:
  input:
    summary_of_element_gene_categories_supplementary_table = "results/supplementary_tables/summary_of_element_gene_categories.tsv",
    k562_guide_targets_supp_table = "results/supplementary_tables/k562_guide_targets_supp_table.tsv",
    wtc11_guide_targets_supp_table = "results/supplementary_tables/wtc11_guide_targets_supp_table.tsv"
  output:
    touch("results/supplementary_tables/create_all_supplementary_tables.done")
